### ISSUE TITLE
Apple TV

### ISSUE THREAD

**Issue by AR-Tawil** [n1k0m0/BackLight#1]
Hi

Great project,...
Can I ask you please if your code would work with my Apple TV and how to connect it?

Thanks
AR Tawil

**Comment by n1k0m0** [comment]
Hiho,
The architecture is based on Windows/Arduino. You would have to create an analysis program within the apple tv that analyzes the picture and sends the pixel/led color to the arduino server. I dont know if this is possible with apple tv -- but i asume it is probably not possible,
